repositories:
  - https://github.com/bob-ros2/bob_llm
  - https://github.com/bob-ros2/bob_launch

# Mastermind configuration
master_name: Mastermind
default_category: assistant

ros:
  setups:
    - /opt/ros/humble/setup.bash
    - ./ros2_ws/install/setup.bash

# Chat Settings
chat:
  oai:
    max_tool_calls: 5

# Orchestration Settings
orchestration:
  mode: "swarm"         # Options: host, swarm
  image: "bob-nexus:latest"
  network: "alpha"
  discovery_server: null # e.g., "172.18.0.2:11811" if using a Discovery Server
  #domain_id: 42
  compose_file: "master/templates/blueprint.yaml" # Default template for entities

# Default Skills for entities by category
skills:
  master:
    - ["core", "memory"]
    - ["core", "sdlviz"]
    - ["core", "send_matrix"]
  assistant:
    - ["core", "memory"]
  defaults:
    - ["core", "memory"]
